. /etc/pcp.env
pmnsdel hinv.map.dmname 
pmnsdel hinv.map.mdname 
pmnsdel hinv.cpu.frequency_scaling.time 
pmnsdel mem.util.shared 
pmnsdel mem.util.highTotal 
pmnsdel mem.util.highFree 
pmnsdel mem.util.lowTotal 
pmnsdel mem.util.lowFree 
pmnsdel mem.util.reverseMaps 
pmnsdel mem.util.mmap_copy 
pmnsdel mem.util.quicklists 
pmnsdel mem.numa.max_bandwidth 
pmnsdel mem.numa.util.highTotal 
pmnsdel mem.numa.util.highFree 
pmnsdel mem.numa.util.lowTotal 
pmnsdel mem.numa.util.lowFree 
pmnsdel mem.vmstat.allocstall 
pmnsdel mem.vmstat.allocstall_high 
pmnsdel mem.vmstat.compact_blocks_moved 
pmnsdel mem.vmstat.compact_pagemigrate_failed 
pmnsdel mem.vmstat.compact_pages_moved 
pmnsdel mem.vmstat.kswapd_skip_congestion_wait 
pmnsdel mem.vmstat.kswapd_steal 
pmnsdel mem.vmstat.nr_foll_pin_acquired 
pmnsdel mem.vmstat.nr_foll_pin_released 
pmnsdel mem.vmstat.nr_pages_scanned 
pmnsdel mem.vmstat.pgalloc_high 
pmnsdel mem.vmstat.pgrefill_dma32 
pmnsdel mem.vmstat.pgrefill_movable 
pmnsdel mem.vmstat.pgrefill_dma 
pmnsdel mem.vmstat.pgrefill_high 
pmnsdel mem.vmstat.pgrefill_normal 
pmnsdel mem.vmstat.pgscan_direct_dma 
pmnsdel mem.vmstat.pgscan_direct_dma32 
pmnsdel mem.vmstat.pgscan_direct_high 
pmnsdel mem.vmstat.pgscan_direct_movable 
pmnsdel mem.vmstat.pgscan_direct_normal 
pmnsdel mem.vmstat.pgscan_kswapd_dma 
pmnsdel mem.vmstat.pgscan_kswapd_dma32 
pmnsdel mem.vmstat.pgscan_kswapd_high 
pmnsdel mem.vmstat.pgscan_kswapd_movable 
pmnsdel mem.vmstat.pgscan_kswapd_normal 
pmnsdel mem.vmstat.pgsteal_dma 
pmnsdel mem.vmstat.pgsteal_dma32 
pmnsdel mem.vmstat.pgsteal_file 
pmnsdel mem.vmstat.pgsteal_high 
pmnsdel mem.vmstat.pgsteal_movable 
pmnsdel mem.vmstat.pgsteal_normal 
pmnsdel mem.vmstat.pgsteal_kswapd_dma 
pmnsdel mem.vmstat.pgsteal_kswapd_dma32 
pmnsdel mem.vmstat.pgsteal_kswapd_normal 
pmnsdel mem.vmstat.pgsteal_kswapd_movable 
pmnsdel mem.vmstat.pgsteal_direct_dma 
pmnsdel mem.vmstat.pgsteal_direct_dma32 
pmnsdel mem.vmstat.pgsteal_direct_normal 
pmnsdel mem.vmstat.pgsteal_direct_movable 
pmnsdel mem.vmstat.thp_fault_fallback_charge 
pmnsdel mem.vmstat.unevictable_pgs_mlockfreed 
pmnsdel mem.zoneinfo.scanned 
pmnsdel mem.zoneinfo.nr_free_pages 
pmnsdel mem.zoneinfo.nr_alloc_batch 
pmnsdel mem.zoneinfo.cma 
pmnsdel mem.zoneinfo.nr_swapcached 
pmnsdel mem.zoneinfo.nr_foll_pin_acquired 
pmnsdel mem.zoneinfo.nr_foll_pin_released 
pmnsdel mem.zoneinfo.workingset_refault_anon 
pmnsdel mem.zoneinfo.workingset_refault_file 
pmnsdel mem.zoneinfo.workingset_active_anon 
pmnsdel mem.zoneinfo.workingset_active_file 
pmnsdel mem.zoneinfo.workingset_restore_anon 
pmnsdel mem.zoneinfo.workingset_restore_file 
pmnsdel swap.in 
pmnsdel swap.out 
pmnsdel network.tcp.pawspassiverejected 
pmnsdel network.tcp.prequeued 
pmnsdel network.tcp.directcopyfrombacklog 
pmnsdel network.tcp.directcopyfromprequeue 
pmnsdel network.tcp.prequeueddropped 
pmnsdel network.tcp.hphitstouser 
pmnsdel network.tcp.fackreorder 
pmnsdel network.tcp.forwardretrans 
pmnsdel network.tcp.schedulerfail 
pmnsdel network.tcp.tcptimeoutrehash 
pmnsdel network.tcp.tcpduplicatedatarehash 
pmnsdel network.tcp.tcpdsackrecvsegs 
pmnsdel network.tcp.tcpdsackignoreddubious 
pmnsdel network.tcp.tcpmigratereqsuccess 
pmnsdel network.tcp.tcpmigratereqfailure 
pmnsdel network.tcp.tcploss 
pmnsdel network.udp.memerrors 
pmnsdel network.udplite.memerrors 
pmnsdel network.mptcp.mpcapablesynrx 
pmnsdel network.mptcp.mpcapableackrx 
pmnsdel network.mptcp.mpcapablefallbackack 
pmnsdel network.mptcp.mpcapablefallbacksynack 
pmnsdel network.mptcp.mptcpretrans 
pmnsdel network.mptcp.mpjoinnotokenfound 
pmnsdel network.mptcp.mpjoinsynrx 
pmnsdel network.mptcp.mpjoinsynackrx 
pmnsdel network.mptcp.mpjoinsynackhmacfailure 
pmnsdel network.mptcp.mpjoinackrx 
pmnsdel network.mptcp.mpjoinackhmacfailure 
pmnsdel network.mptcp.dssnotmatching 
pmnsdel network.mptcp.infinitemaprx 
pmnsdel network.mptcp.mpcapablesyntx 
pmnsdel network.mptcp.mpcapablesynackrx 
pmnsdel network.mptcp.mpfallbacktokeninit 
pmnsdel network.mptcp.dssnomatchtcp 
pmnsdel network.mptcp.datacsumerr 
pmnsdel network.mptcp.ofoqueuetail 
pmnsdel network.mptcp.ofoqueue 
pmnsdel network.mptcp.ofomerge 
pmnsdel network.mptcp.nodssinwindow 
pmnsdel network.mptcp.duplicatedata 
pmnsdel network.mptcp.addaddr 
pmnsdel network.mptcp.echoadd 
pmnsdel network.mptcp.portadd 
pmnsdel network.mptcp.mpjoinportsynrx 
pmnsdel network.mptcp.mpjoinportsynackrx 
pmnsdel network.mptcp.mpjoinportackrx 
pmnsdel network.mptcp.mismatchportsynrx 
pmnsdel network.mptcp.mismatchportackrx 
pmnsdel network.mptcp.rmaddr 
pmnsdel network.mptcp.rmsubflow 
pmnsdel network.mptcp.mppriotx 
pmnsdel network.mptcp.mppriorx 
pmnsdel network.mptcp.rcvpruned 
pmnsdel network.mptcp.mpfailtx 
pmnsdel network.mptcp.mpfailrx 
pmnsdel network.mptcp.subflowstale 
pmnsdel network.mptcp.subflowrecover 
pmnsdel network.mptcp.addaddrdrop 
pmnsdel network.mptcp.rmaddrdrop 
pmnsdel disk.dm.read 
pmnsdel disk.dm.write 
pmnsdel disk.dm.total 
pmnsdel disk.dm.blkread 
pmnsdel disk.dm.blkwrite 
pmnsdel disk.dm.blktotal 
pmnsdel disk.dm.read_bytes 
pmnsdel disk.dm.write_bytes 
pmnsdel disk.dm.total_bytes 
pmnsdel disk.dm.read_merge 
pmnsdel disk.dm.write_merge 
pmnsdel disk.dm.avactive 
pmnsdel disk.dm.aveq 
pmnsdel disk.dm.read_rawactive 
pmnsdel disk.dm.write_rawactive 
pmnsdel disk.dm.total_rawactive 
pmnsdel disk.dm.capacity 
pmnsdel disk.dm.discard 
pmnsdel disk.dm.blkdiscard 
pmnsdel disk.dm.discard_bytes 
pmnsdel disk.dm.discard_merge 
pmnsdel disk.dm.discard_rawactive 
pmnsdel disk.dm.flush 
pmnsdel disk.dm.flush_rawactive 
pmnsdel disk.md.read 
pmnsdel disk.md.write 
pmnsdel disk.md.total 
pmnsdel disk.md.blkread 
pmnsdel disk.md.blkwrite 
pmnsdel disk.md.blktotal 
pmnsdel disk.md.read_bytes 
pmnsdel disk.md.write_bytes 
pmnsdel disk.md.total_bytes 
pmnsdel disk.md.read_merge 
pmnsdel disk.md.write_merge 
pmnsdel disk.md.avactive 
pmnsdel disk.md.aveq 
pmnsdel disk.md.read_rawactive 
pmnsdel disk.md.write_rawactive 
pmnsdel disk.md.total_rawactive 
pmnsdel disk.md.status 
pmnsdel disk.md.capacity 
pmnsdel disk.md.discard 
pmnsdel disk.md.blkdiscard 
pmnsdel disk.md.discard_bytes 
pmnsdel disk.md.discard_merge 
pmnsdel disk.md.discard_rawactive 
pmnsdel disk.md.flush 
pmnsdel disk.md.flush_rawactive 
pmnsdel disk.wwid.capacity 
pmnsdel rpc.client.rpccnt 
pmnsdel rpc.client.rpcretrans 
pmnsdel rpc.client.rpcauthrefresh 
pmnsdel rpc.client.netcnt 
pmnsdel rpc.client.netudpcnt 
pmnsdel rpc.client.nettcpcnt 
pmnsdel rpc.client.nettcpconn 
pmnsdel rpc.server.rpccnt 
pmnsdel rpc.server.rpcerr 
pmnsdel rpc.server.rpcbadfmt 
pmnsdel rpc.server.rpcbadauth 
pmnsdel rpc.server.rpcbadclnt 
pmnsdel rpc.server.rchits 
pmnsdel rpc.server.rcmisses 
pmnsdel rpc.server.rcnocache 
pmnsdel rpc.server.fh_cached 
pmnsdel rpc.server.fh_valid 
pmnsdel rpc.server.fh_fixup 
pmnsdel rpc.server.fh_lookup 
pmnsdel rpc.server.fh_stale 
pmnsdel rpc.server.fh_concurrent 
pmnsdel rpc.server.netcnt 
pmnsdel rpc.server.netudpcnt 
pmnsdel rpc.server.nettcpcnt 
pmnsdel rpc.server.nettcpconn 
pmnsdel rpc.server.fh_anon 
pmnsdel rpc.server.fh_nocache_dir 
pmnsdel rpc.server.fh_nocache_nondir 
pmnsdel rpc.server.io_read 
pmnsdel rpc.server.io_write 
pmnsdel rpc.server.th_cnt 
pmnsdel rpc.server.th_fullcnt 
pmnsdel nfs.client.calls 
pmnsdel nfs.client.reqs 
pmnsdel nfs.server.calls 
pmnsdel nfs.server.reqs 
pmnsdel nfs.server.threads.total 
pmnsdel nfs.server.threads.pools 
pmnsdel nfs.server.threads.requests 
pmnsdel nfs.server.threads.enqueued 
pmnsdel nfs.server.threads.processed 
pmnsdel nfs.server.threads.timedout 
pmnsdel nfs3.client.calls 
pmnsdel nfs3.client.reqs 
pmnsdel nfs3.server.calls 
pmnsdel nfs3.server.reqs 
pmnsdel nfs4.client.calls 
pmnsdel nfs4.client.reqs 
pmnsdel nfs4.server.calls 
pmnsdel nfs4.server.reqs 
pmnsdel ipc.sem.key 
pmnsdel ipc.sem.owner 
pmnsdel ipc.sem.perms 
pmnsdel ipc.sem.nsems 
pmnsdel ipc.msg.key 
pmnsdel ipc.msg.owner 
pmnsdel ipc.msg.perms 
pmnsdel ipc.msg.msgsz 
pmnsdel ipc.msg.messages 
pmnsdel ipc.msg.last_send_pid 
pmnsdel ipc.msg.last_recv_pid 
pmnsdel tape.dev.in_flight 
pmnsdel tape.dev.io_ns 
pmnsdel tape.dev.other_cnt 
pmnsdel tape.dev.read_byte_cnt 
pmnsdel tape.dev.read_cnt 
pmnsdel tape.dev.read_ns 
pmnsdel tape.dev.resid_cnt 
pmnsdel tape.dev.write_byte_cnt 
pmnsdel tape.dev.write_cnt 
pmnsdel tape.dev.write_ns 
pmnsdel zram.read 
pmnsdel zram.write 
pmnsdel zram.total 
pmnsdel zram.blkread 
pmnsdel zram.blkwrite 
pmnsdel zram.blktotal 
pmnsdel zram.read_bytes 
pmnsdel zram.write_bytes 
pmnsdel zram.total_bytes 
pmnsdel zram.read_merge 
pmnsdel zram.write_merge 
pmnsdel zram.avactive 
pmnsdel zram.aveq 
pmnsdel zram.read_rawactive 
pmnsdel zram.write_rawactive 
pmnsdel zram.total_rawactive 
pmnsdel zram.capacity 
pmnsdel zram.discard 
pmnsdel zram.blkdiscard 
pmnsdel zram.discard_bytes 
pmnsdel zram.discard_merge 
pmnsdel zram.discard_rawactive 
pmnsdel zram.flush 
pmnsdel zram.flush_rawactive 
pmnsdel zram.io_stat.invalid 
pmnsdel zram.io_stat.notify_free 
pmnsdel zram.io_stat.failed.reads 
pmnsdel zram.io_stat.failed.writes 
pmnsdel zram.mm_stat.data_size.original 
pmnsdel zram.mm_stat.data_size.compressed 
pmnsdel zram.mm_stat.mem.used_total 
pmnsdel zram.mm_stat.mem.limit 
pmnsdel zram.mm_stat.mem.max_used 
pmnsdel zram.mm_stat.pages.same 
pmnsdel zram.mm_stat.pages.compacted 
pmnsdel zram.mm_stat.pages.huge 
pmnsdel zram.bd_stat.count 
pmnsdel zram.bd_stat.reads 
pmnsdel zram.bd_stat.writes 
pmnsdel fchost.lip_count 
pmnsdel fchost.nos_count 
pmnsdel fchost.error_frames 
pmnsdel fchost.dumped_frames 
pmnsdel fchost.in.frames 
pmnsdel fchost.in.bytes 
pmnsdel fchost.out.frames 
pmnsdel fchost.out.bytes 
pmnsdel pmcd.pmie.configfile 
pmnsdel pmcd.pmie.logfile 
pmnsdel pmcd.pmie.pmcd_host 
pmnsdel pmcd.pmie.numrules 
pmnsdel pmcd.pmie.actions 
pmnsdel pmcd.pmie.eval.true 
pmnsdel pmcd.pmie.eval.false 
pmnsdel pmcd.pmie.eval.unknown 
pmnsdel pmcd.pmie.eval.expected 
pmnsdel pmcd.pmie.eval.actual 
pmnsdel cgroup.cpu.stat.user 
pmnsdel cgroup.cpu.stat.system 
pmnsdel cgroup.cpu.stat.usage 
pmnsdel cgroup.cpusched.cfs_quota 
pmnsdel cgroup.memory.current 
pmnsdel cgroup.memory.stat.swap 
pmnsdel cgroup.memory.stat.anon 
pmnsdel cgroup.memory.stat.anon_thp 
pmnsdel cgroup.memory.stat.file 
pmnsdel cgroup.memory.stat.file_dirty 
pmnsdel cgroup.memory.stat.file_mapped 
pmnsdel cgroup.memory.stat.file_writeback 
pmnsdel cgroup.memory.stat.kernel_stack 
pmnsdel cgroup.memory.stat.pgactivate 
pmnsdel cgroup.memory.stat.pgdeactivate 
pmnsdel cgroup.memory.stat.pglazyfree 
pmnsdel cgroup.memory.stat.pglazyfreed 
pmnsdel cgroup.memory.stat.pgrefill 
pmnsdel cgroup.memory.stat.pgscan 
pmnsdel cgroup.memory.stat.pgsteal 
pmnsdel cgroup.memory.stat.slab 
pmnsdel cgroup.memory.stat.slab_reclaimable 
pmnsdel cgroup.memory.stat.slab_unreclaimable 
pmnsdel cgroup.memory.stat.sock 
pmnsdel cgroup.memory.stat.thp_collapse_alloc 
pmnsdel cgroup.memory.stat.thp_fault_alloc 
pmnsdel cgroup.memory.stat.total.swap 
pmnsdel cgroup.memory.stat.recent.rotated_anon 
pmnsdel cgroup.memory.stat.recent.rotated_file 
pmnsdel cgroup.memory.stat.recent.scanned_anon 
pmnsdel cgroup.memory.stat.recent.scanned_file 
pmnsdel cgroup.memory.stat.workingset.activate 
pmnsdel cgroup.memory.stat.workingset.nodereclaim 
pmnsdel cgroup.memory.stat.workingset.refault 
pmnsdel cgroup.netclass.classid 
pmnsdel cgroup.pressure.cpu.some.avg10sec 
pmnsdel cgroup.pressure.cpu.some.avg1min 
pmnsdel cgroup.pressure.cpu.some.avg5min 
pmnsdel cgroup.pressure.cpu.some.total 
pmnsdel cgroup.pressure.memory.some.avg10sec 
pmnsdel cgroup.pressure.memory.some.avg1min 
pmnsdel cgroup.pressure.memory.some.avg5min 
pmnsdel cgroup.pressure.memory.some.total 
pmnsdel cgroup.pressure.memory.full.avg10sec 
pmnsdel cgroup.pressure.memory.full.avg1min 
pmnsdel cgroup.pressure.memory.full.avg5min 
pmnsdel cgroup.pressure.memory.full.total 
pmnsdel cgroup.pressure.io.some.avg10sec 
pmnsdel cgroup.pressure.io.some.avg1min 
pmnsdel cgroup.pressure.io.some.avg5min 
pmnsdel cgroup.pressure.io.some.total 
pmnsdel cgroup.pressure.io.full.avg10sec 
pmnsdel cgroup.pressure.io.full.avg1min 
pmnsdel cgroup.pressure.io.full.avg5min 
pmnsdel cgroup.pressure.io.full.total 
pmnsdel cgroup.io.stat.rbytes 
pmnsdel cgroup.io.stat.wbytes 
pmnsdel cgroup.io.stat.rios 
pmnsdel cgroup.io.stat.wios 
pmnsdel cgroup.io.stat.dbytes 
pmnsdel cgroup.io.stat.dios 
pmnsdel proc.namespaces.envid 
pmnsdel hotproc.psinfo.cwd 
pmnsdel hotproc.psinfo.exe 
pmnsdel hotproc.psinfo.oom_score 
pmnsdel hotproc.psinfo.tgid 
pmnsdel hotproc.psinfo.ngid 
pmnsdel hotproc.psinfo.cpusallowed 
pmnsdel hotproc.psinfo.nvctxsw 
pmnsdel hotproc.psinfo.vctxsw 
pmnsdel hotproc.psinfo.labels 
pmnsdel hotproc.psinfo.cgroups 
pmnsdel hotproc.psinfo.threads 
pmnsdel hotproc.psinfo.sigcatch_s 
pmnsdel hotproc.psinfo.sigignore_s 
pmnsdel hotproc.psinfo.blocked_s 
pmnsdel hotproc.psinfo.signal_s 
pmnsdel hotproc.psinfo.policy_s 
pmnsdel hotproc.psinfo.environ 
pmnsdel hotproc.psinfo.cguest_time 
pmnsdel hotproc.psinfo.guest_time 
pmnsdel hotproc.psinfo.delayacct_blkio_time 
pmnsdel hotproc.psinfo.policy 
pmnsdel hotproc.psinfo.rt_priority 
pmnsdel hotproc.psinfo.psargs 
pmnsdel hotproc.psinfo.wchan_s 
pmnsdel hotproc.psinfo.ttyname 
pmnsdel hotproc.psinfo.processor 
pmnsdel hotproc.psinfo.exit_signal 
pmnsdel hotproc.psinfo.cnswap 
pmnsdel hotproc.psinfo.nswap 
pmnsdel hotproc.psinfo.wchan 
pmnsdel hotproc.psinfo.sigcatch 
pmnsdel hotproc.psinfo.sigignore 
pmnsdel hotproc.psinfo.blocked 
pmnsdel hotproc.psinfo.signal 
pmnsdel hotproc.psinfo.eip 
pmnsdel hotproc.psinfo.esp 
pmnsdel hotproc.psinfo.start_stack 
pmnsdel hotproc.psinfo.end_code 
pmnsdel hotproc.psinfo.start_code 
pmnsdel hotproc.psinfo.rss_rlim 
pmnsdel hotproc.psinfo.rss 
pmnsdel hotproc.psinfo.vsize 
pmnsdel hotproc.psinfo.start_time 
pmnsdel hotproc.psinfo.it_real_value 
pmnsdel hotproc.psinfo.nice 
pmnsdel hotproc.psinfo.priority 
pmnsdel hotproc.psinfo.cstime 
pmnsdel hotproc.psinfo.cutime 
pmnsdel hotproc.psinfo.stime 
pmnsdel hotproc.psinfo.utime 
pmnsdel hotproc.psinfo.cmaj_flt 
pmnsdel hotproc.psinfo.maj_flt 
pmnsdel hotproc.psinfo.cmin_flt 
pmnsdel hotproc.psinfo.minflt 
pmnsdel hotproc.psinfo.flags 
pmnsdel hotproc.psinfo.tty_pgrp 
pmnsdel hotproc.psinfo.tty 
pmnsdel hotproc.psinfo.session 
pmnsdel hotproc.psinfo.pgrp 
pmnsdel hotproc.psinfo.ppid 
pmnsdel hotproc.psinfo.sname 
pmnsdel hotproc.psinfo.cmd 
pmnsdel hotproc.psinfo.pid 
pmnsdel hotproc.memory.vmnonlib 
pmnsdel hotproc.memory.vmreal 
pmnsdel hotproc.memory.vmpte 
pmnsdel hotproc.memory.vmhwm 
pmnsdel hotproc.memory.vmpin 
pmnsdel hotproc.memory.vmpeak 
pmnsdel hotproc.memory.vmswap 
pmnsdel hotproc.memory.vmlib 
pmnsdel hotproc.memory.vmexe 
pmnsdel hotproc.memory.vmstack 
pmnsdel hotproc.memory.vmdata 
pmnsdel hotproc.memory.vmrss 
pmnsdel hotproc.memory.vmlock 
pmnsdel hotproc.memory.vmsize 
pmnsdel hotproc.memory.maps 
pmnsdel hotproc.memory.dirty 
pmnsdel hotproc.memory.datrss 
pmnsdel hotproc.memory.librss 
pmnsdel hotproc.memory.textrss 
pmnsdel hotproc.memory.share 
pmnsdel hotproc.memory.rss 
pmnsdel hotproc.memory.size 
pmnsdel hotproc.id.container 
pmnsdel hotproc.id.fsgid_nm 
pmnsdel hotproc.id.sgid_nm 
pmnsdel hotproc.id.egid_nm 
pmnsdel hotproc.id.gid_nm 
pmnsdel hotproc.id.fsuid_nm 
pmnsdel hotproc.id.suid_nm 
pmnsdel hotproc.id.euid_nm 
pmnsdel hotproc.id.uid_nm 
pmnsdel hotproc.id.fsgid 
pmnsdel hotproc.id.sgid 
pmnsdel hotproc.id.egid 
pmnsdel hotproc.id.gid 
pmnsdel hotproc.id.fsuid 
pmnsdel hotproc.id.suid 
pmnsdel hotproc.id.euid 
pmnsdel hotproc.id.uid 
pmnsdel hotproc.io.cancelled_write_bytes 
pmnsdel hotproc.io.write_bytes 
pmnsdel hotproc.io.read_bytes 
pmnsdel hotproc.io.syscw 
pmnsdel hotproc.io.syscr 
pmnsdel hotproc.io.wchar 
pmnsdel hotproc.io.rchar 
pmnsdel hotproc.schedstat.pcount 
pmnsdel hotproc.schedstat.run_delay 
pmnsdel hotproc.schedstat.cpu_time 
pmnsdel hotproc.fd.count 
pmnsdel hotproc.namespaces.envid 
pmnsdel hotproc.namespaces.sid 
pmnsdel hotproc.namespaces.pgid 
pmnsdel hotproc.namespaces.pid 
pmnsdel hotproc.namespaces.tgid 
pmnsdel hotproc.smaps.locked 
pmnsdel hotproc.smaps.swappss 
pmnsdel hotproc.smaps.swap 
pmnsdel hotproc.smaps.private_hugetlb 
pmnsdel hotproc.smaps.shared_hugetlb 
pmnsdel hotproc.smaps.filepmdmapped 
pmnsdel hotproc.smaps.shmempmdmapped 
pmnsdel hotproc.smaps.anonhugepages 
pmnsdel hotproc.smaps.lazyfree 
pmnsdel hotproc.smaps.anonymous 
pmnsdel hotproc.smaps.referenced 
pmnsdel hotproc.smaps.private_dirty 
pmnsdel hotproc.smaps.private_clean 
pmnsdel hotproc.smaps.shared_dirty 
pmnsdel hotproc.smaps.shared_clean 
pmnsdel hotproc.smaps.pss_shmem 
pmnsdel hotproc.smaps.pss_file 
pmnsdel hotproc.smaps.pss_anon 
pmnsdel hotproc.smaps.pss 
pmnsdel hotproc.smaps.rss 
pmnsdel hotproc.autogroup.nice 
pmnsdel hotproc.autogroup.id 
pmnsdel hotproc.predicate.ctxswitch 
pmnsdel hotproc.predicate.virtualsize 
pmnsdel hotproc.predicate.residentsize 
pmnsdel hotproc.predicate.iodemand 
pmnsdel hotproc.predicate.iowait 
pmnsdel hotproc.predicate.schedwait 
pmnsdel hotproc.predicate.cpuburn 
pmnsdel acct.psinfo.tty 
pmnsdel acct.psinfo.exitcode 
pmnsdel acct.psinfo.pid 
pmnsdel acct.psinfo.ppid 
pmnsdel acct.psinfo.btime 
pmnsdel acct.psinfo.etime 
pmnsdel acct.psinfo.utime 
pmnsdel acct.psinfo.stime 
pmnsdel acct.psinfo.mem 
pmnsdel acct.psinfo.io 
pmnsdel acct.psinfo.rw 
pmnsdel acct.psinfo.minflt 
pmnsdel acct.psinfo.majflt 
pmnsdel acct.psinfo.swaps 
pmnsdel acct.psinfo.ttyname 
pmnsdel acct.id.uid 
pmnsdel acct.id.gid 
pmnsdel acct.id.uid_nm 
pmnsdel acct.id.gid_nm 
pmnsdel acct.flag.fork 
pmnsdel acct.flag.su 
pmnsdel acct.flag.core 
pmnsdel acct.flag.xsig 
pmnsdel containers.engine 
pmnsdel containers.name 
pmnsdel containers.pid 
pmnsdel containers.cgroup 
pmnsdel containers.state.running 
pmnsdel containers.state.paused 
pmnsdel containers.state.restarting 
pmnsdel event.flags 
pmnsdel event.missed 
pmnsdel disk.dev.await 
pmnsdel disk.dev.r_await 
pmnsdel disk.dev.w_await 
pmnsdel disk.dev.d_await 
pmnsdel disk.dev.f_await 
pmnsdel disk.dev.avg_qlen 
pmnsdel disk.dev.avg_rqsz 
pmnsdel disk.dev.r_avg_rqsz 
pmnsdel disk.dev.w_avg_rqsz 
pmnsdel disk.dev.d_avg_rqsz 
pmnsdel disk.dev.util 
pmnsdel disk.dm.await 
pmnsdel disk.dm.r_await 
pmnsdel disk.dm.w_await 
pmnsdel disk.dm.d_await 
pmnsdel disk.dm.f_await 
pmnsdel disk.dm.avg_qlen 
pmnsdel disk.dm.avg_rqsz 
pmnsdel disk.dm.r_avg_rqsz 
pmnsdel disk.dm.w_avg_rqsz 
pmnsdel disk.dm.d_avg_rqsz 
pmnsdel disk.dm.util 
pmnsdel disk.md.await 
pmnsdel disk.md.r_await 
pmnsdel disk.md.w_await 
pmnsdel disk.md.d_await 
pmnsdel disk.md.f_await 
pmnsdel disk.md.avg_qlen 
pmnsdel disk.md.avg_rqsz 
pmnsdel disk.md.r_avg_rqsz 
pmnsdel disk.md.w_avg_rqsz 
pmnsdel disk.md.d_avg_rqsz 
pmnsdel disk.md.util 
pmnsdel disk.wwid.await 
pmnsdel disk.wwid.r_await 
pmnsdel disk.wwid.w_await 
pmnsdel disk.wwid.d_await 
pmnsdel disk.wwid.f_await 
pmnsdel disk.wwid.avg_qlen 
pmnsdel disk.wwid.avg_rqsz 
pmnsdel disk.wwid.r_avg_rqsz 
pmnsdel disk.wwid.w_avg_rqsz 
pmnsdel disk.wwid.d_avg_rqsz 
pmnsdel disk.wwid.util 
pmnsdel kernel.cpu.util.user 
pmnsdel kernel.cpu.util.nice 
pmnsdel kernel.cpu.util.sys 
pmnsdel kernel.cpu.util.idle 
pmnsdel kernel.cpu.util.intr 
pmnsdel kernel.cpu.util.wait 
pmnsdel kernel.cpu.util.steal 
pmnsdel proc.hog.cpu 
pmnsdel proc.hog.disk 
$PCP_RC_DIR/pmcd start
